name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: validating testcases
      run: make safecheck
    - name: print report to log
      run: cat testcases/out/report.txt
    - name: uploading report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: testcases/out/report.txt
    - name: uploading LaTeX files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: LaTeX-files
        path: debug
    - name: reporting result
      run: make check
